// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArjtObj7tOFm1pV6jfaWP2CsDgV0nQ2fg',
    appId: '1:527630933903:web:2d9bcc96a006b8817bf5fa',
    messagingSenderId: '527630933903',
    projectId: 'auth-counter-app',
    authDomain: 'auth-counter-app.firebaseapp.com',
    storageBucket: 'auth-counter-app.firebasestorage.app',
    measurementId: 'G-YEH72NR3MZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM9938gs0zH5x-NH43HALJ1V9QQ1b6_sM',
    appId: '1:527630933903:android:f6ab9f50ca3731757bf5fa',
    messagingSenderId: '527630933903',
    projectId: 'auth-counter-app',
    storageBucket: 'auth-counter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX3W_-7FJwpdruBOSuLJw7HO5dEPX4aAY',
    appId: '1:527630933903:ios:9638b6f16c84fb677bf5fa',
    messagingSenderId: '527630933903',
    projectId: 'auth-counter-app',
    storageBucket: 'auth-counter-app.firebasestorage.app',
    iosBundleId: 'com.example.smartIncAuthapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX3W_-7FJwpdruBOSuLJw7HO5dEPX4aAY',
    appId: '1:527630933903:ios:9638b6f16c84fb677bf5fa',
    messagingSenderId: '527630933903',
    projectId: 'auth-counter-app',
    storageBucket: 'auth-counter-app.firebasestorage.app',
    iosBundleId: 'com.example.smartIncAuthapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArjtObj7tOFm1pV6jfaWP2CsDgV0nQ2fg',
    appId: '1:527630933903:web:9c2b5fbc1bfca46a7bf5fa',
    messagingSenderId: '527630933903',
    projectId: 'auth-counter-app',
    authDomain: 'auth-counter-app.firebaseapp.com',
    storageBucket: 'auth-counter-app.firebasestorage.app',
    measurementId: 'G-6S16HB9M8Q',
  );
}
